### ISSUE TITLE
Alter Continuous Integration Pipeline

### ISSUE THREAD

**Issue by elbeejay** [worldbank/climateknowledgeportal#11]
Capturing ideas from #10:

>>@g4brielvs - does the actions workflow not run for PRs? If so please test locally and if it works for both of us then maybe we can merge and hope it works live on the main branch.

>@elbeejay Thanks! I was going to send you an example; you were the fastest 🚀. It won't. The workflow is [set up to only be triggered on pushes against main](https://github.com/worldbank/climateknowledgeportal/blob/e5f8ee438205d710e93832e650b4c3b32ec8f4f3/.github/workflows/gh-pages.yml#L3).

>True - we might want to consider changing the yml recipe to run all of the stages except the deploy stage for pull requests and branches. Not a huge deal, but could help us test the workflow when making bigger changes like this.

>That's a good point. Also, I was thinking we may want to create a workflow separate from [gh-pages](https://github.com/worldbank/climateknowledgeportal/blob/main/.github/workflows/gh-pages.yml) for the collection documentation.

**Comment by g4brielvs** [comment]
@elbeejay Thanks for opening this issue. It was more like an idea that it could be helpful to version the collection file structures by creating a separate workflow alongside to commit the content to the repository and make them visible on GitHub as well. Then [gh-pages](https://github.com/worldbank/climateknowledgeportal/actions/workflows/gh-pages.yml) would build the page. However, at this time (or maybe ever), it would probably be an overkill. It'd be better to keep it simple. What do you think?

**Comment by elbeejay** [comment]
Closing as we never felt a need to change the existing pipeline.
