### ISSUE TITLE
Expand Examples

### ISSUE THREAD

**Issue by g4brielvs** [worldbank/climateknowledgeportal#5]
This issue is to update and examples with the CCKP netCDF data.

**Comment by elbeejay** [comment]
@g4brielvs should I go ahead and finish the example now that we have an sample `.nc` file?

**Comment by g4brielvs** [comment]
@elbeejay Yes. Please go ahead and revert in case of any questions.

**Comment by elbeejay** [comment]
> @elbeejay Yes. Please go ahead and revert in case of any questions.

@g4brielvs I've opened #8 as a draft with my plan for expanding the examples. I've added information about the dataset as text at the top (time, resolution, variables) and then expanded the code example to showcase accessing the data and then plotting it. Take a look and let me know if something like this is what you had in mind. If so, I'll go ahead and flesh out the rest of the examples tomorrow, if not we can work towards something better.

Thanks

**Comment by elbeejay** [comment]
Since we merged #8, I think we are just waiting to hear if the CCKP team wants to see additional or different examples, does that sound correct @g4brielvs?

**Comment by g4brielvs** [comment]
> I think we are just waiting to hear if the CCKP team wants to see additional or different examples

Could you please follow up with the CCKP?

**Comment by elbeejay** [comment]
> > I think we are just waiting to hear if the CCKP team wants to see additional or different examples
> 
> Could you please follow up with the CCKP?

Revisions made to documentation in #13 per CCKP team request.
